name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - notice-dev
      - cicd-flow-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        # Install pnpm
      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node

        # Install Package dependencies
      - name: Install Dependencies
        run: pnpm install

        # Testing
      - name: Run Tests
        run: pnpm test

        # Success test >> building
      - name: Build
        run: pnpm run build

        # TODO deploy
      - name: Deploy
